name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: rectorsquid-linkage-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl https://www.rectorsquid.com/linkage.msi -L --output linkage.msi &&^
          dir
          
      - name: lessmsi 
        shell: cmd
        run: | 
          curl https://github.com/activescott/lessmsi/releases/download/v1.10.0/lessmsi-v1.10.0.zip -L --output lessmsi.zip && 7z.exe x lessmsi.zip -o"lessmsi"
          
      - name: uncompress msi
        shell: cmd
        run: |
          .\lessmsi\lessmsi.exe x "linkage.msi" "installation\"

      - shell: cmd
        run: xcopy /H /Y /C "linkage.exe.Portable.cmd" "installation"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation/SourceDir/Linkage"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/SourceDir/Linkage/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
